name: 'Setup slack env'
description: 'Setup slack env'
inputs:
  repository:  
    description: 'work repository'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository }}
